apiVersion: v1
kind: PersistentVolume
metadata:
  name: jira-efs-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.volume.capacity }}
  accessModes:
    - {{ .Values.volume.accessModes }}
  hostPath:
    path: {{ .Values.volume.hostPath }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jira-efs-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - {{ .Values.volume.accessModes }}
  resources:
    requests:
      storage: {{ .Values.volume.capacity }}
